### ISSUE TITLE
error when try install on Ubuntu 20.04

### ISSUE THREAD

**Issue by mark-91** [cggos/orbslam2_cg#1]
i'm trying to install 
orb_slam2_cg on fresh Ubuntu 
and i have this error
ai@ai:~/orb_slam2_cg/platforms/ros_wrapper$ catkin_make -j1
Base path: /home/ai/orb_slam2_cg/platforms/ros_wrapper
Source space: /home/ai/orb_slam2_cg/platforms/ros_wrapper/src
Build space: /home/ai/orb_slam2_cg/platforms/ros_wrapper/build
Devel space: /home/ai/orb_slam2_cg/platforms/ros_wrapper/devel
Install space: /home/ai/orb_slam2_cg/platforms/ros_wrapper/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ai/orb_slam2_cg/platforms/ros_wrapper/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ai/orb_slam2_cg/platforms/ros_wrapper/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - orbslam2_ros
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'orbslam2_ros'
-- ==> add_subdirectory(orbslam2_ros)
CMake Error at /home/ai/orb_slam2_cg/orbslam2/CMakeLists.txt:60 (find_package):
  By not providing "FindDBoW2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DBoW2", but
  CMake did not find one.

  Could not find a package configuration file provided by "DBoW2" with any of
  the following names:

    DBoW2Config.cmake
    dbow2-config.cmake

  Add the installation prefix of "DBoW2" to CMAKE_PREFIX_PATH or set
  "DBoW2_DIR" to a directory containing one of the above files.  If "DBoW2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ai/orb_slam2_cg/platforms/ros_wrapper/build/CMakeFiles/CMakeOutput.log".
See also "/home/ai/orb_slam2_cg/platforms/ros_wrapper/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 i try to download and build DBoW2 but still not work 
 i put DBoW2 directory in  /home/ai/orb_slam2_cg/Thirdparty/DBoW2
 and libDBoW2.so in /home/ai/orb_slam2_cg/Thirdparty/DBoW2/lib
 i try change CMakeLists.txt:60 to >> 
 find_package(DBoW2 REQUIRED)
list(APPEND LIBS ${PROJECT_SOURCE_DIR}/home/ai/orb_slam2_cg/Thirdparty/DBoW2/lib/libDBoW2.so)
but still not work
thank's

**Comment by cggos** [comment]
@mark-91  Please refer to the README.md
